import 'package:flutter/material.dart';
import 'package:mm_social/dummy/dummy_conversation_function_vo.dart';
import 'package:mm_social/dummy/dummy_message_vo.dart';

List<String> dummyNameList = [
  "United States",
  "Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and/or Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia (Hrvatska)",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecudaor",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "France, Metropolitan",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and Mc Donald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfork Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St. Helena",
  "St. Pierre and Miquelon",
  "Sudan",
  "Suriname",
  "Svalbarn and Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States minor outlying islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City State",
  "Venezuela",
  "Vietnam",
  "Virigan Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Yugoslavia",
  "Zaire",
  "Zambia",
  "Zimbabwe",
];

List<DummyMessageVO> messageList = [
  DummyMessageVO(message: "How are you?", isMe: true),
  DummyMessageVO(message: "I hope you are well and happy", isMe: true),
  DummyMessageVO(message: "I'm fine", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "What are you doing on these days?", isMe: false),
  DummyMessageVO(message: "I went to Pyin Oo Lwin and that is great.", isMe: true),
  DummyMessageVO(message: "Wow! Really. I' am also at the trip brother. I am at Ngwe Saung Beach which is located in Ayeyawaddy Region", isMe: false),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "I have heard that this beach is really beautiful", isMe: true),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
  DummyMessageVO(message: "Long time no see brother", isMe: false),
];

List<DummyConversationFunctionVO> conversationFunctionList = [
  DummyConversationFunctionVO(iconData: Icons.perm_media_outlined, label: "Media"),
  DummyConversationFunctionVO(iconData: Icons.camera_alt_outlined, label: "Camera"),
  DummyConversationFunctionVO(iconData: Icons.insights, label: "Sight"),
  DummyConversationFunctionVO(iconData: Icons.switch_video_outlined, label: "Video Call"),
  DummyConversationFunctionVO(iconData: Icons.attach_money_rounded, label: "Luck Money"),
  DummyConversationFunctionVO(iconData: Icons.transform_rounded, label: "Transfer"),
  DummyConversationFunctionVO(iconData: Icons.favorite, label: "Favourites"),
  DummyConversationFunctionVO(iconData: Icons.location_on_outlined, label: "Location"),
];

List<String> nameList = [
  "Maung Maung",
  "Aung Aung",
  "Thidar",
  "Nilar",
  "Kyi Pyar",
];

Map<String, String> dummyCountryMap = {
  "Afghanistan": "+93",
  "Albania": "+355",
  "Algeria": "+213",
  "American Samoa": "+1684",
  "Andorra": "+376",
  "Argentina": "+54",
  "Armenia": "+374",
  "Aruba": "+297",
  "Austria": "43",
  "Azerbaijan": "+994",
  "Bahamas": "+1242",
  "Bahrain": "+973",
  "Bangladesh": "+880",
  "Barbados": "+1246",
  "Belarus": "+375",
  "Belgium": "+32",
  "Benin": "+229",
  "Bhutan": "+975",
  "Bolivia": "+591",
  "Botswana": "+267",
  "Cambodia": "+855",
  "Cameroon": "+235",
  "Canada": "+1",
  "Cape Verde": "+238",
  "Cayman Islands": "+1345",
  "Central African Republic": "+236",
  "Chad": "+237",
  "Chile": "+56",
  "China": "+86",
  "Christmas Island": "+61",
  "Macau": "+853",
  "Macedonia": "+389",
  "Madagascar": "+261",
  "Malawi": "+265",
  "Malaysia": "+60",
  "Maldives": "+960",
  "Mali": "+223",
  "Malta": "+356",
  "Marshall Islands": "+692",
  "Myanmar": "+95",
  "South Africa": "+27",
  "South Korea": "+82",
  "Taiwan": "+886",
  "Thailand": "+66",
  "United Kingdom": "+44",
  "United States": "+1",
  "Yemen": "+967",
  "Zambia": "+260",
  "Zimbabwe": "+263",
};
